#' robspdep generated dataset
#'
#' Data is generated considering a 10-by-10 regular square lattice grid where data is generated by
#' a spatial autoregressive process with a strong spatial correlation parameter (rho = 0.7)
#' obtained by filtering a random sample generated by 100 independent standard normal distributions.
#' The outcoming x variable is associated to a Moran test of 0.65 which is highly significant (p-value < 2.2e-16)
#' The variable y is then contaminated with just one single outlier (=50) located in the upper left corner.
#' The new map is now characterized by a much lower value of the  Moran test of (0.199) which is not significant (p-value = 0.42).
#' Therefore the presence of a single ouliers totally rubs off the strong spatial correlation structure
#' that was evident before the contamination.
#'
#' @format A list containing:
#' \describe{
#'   \item{x}{uncontaminated variable}
#'   \item{y}{contaminated variable}
#'   \item{w}{10-by-10 regular square lattice grid in spdep list w object}
#' }
"sampledata"
